services:
  tanstack-rsc:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: tanstack_app
    ports:
      - '3000:3000'
    env_file:
      - .env
    # environment:
    ## internal (for Next.js backend â†’ MediaMTX)
    restart: always
